// Client-side types (re-exports from shared + client-specific)
export type {
    UserRole,
    AdvocateTier,
    CampaignStatus,
    CampaignType,
    Platform,
    ContentType,
    ScoringStatus,
    ReviewStatus,
    FraudRiskLevel,
    Profile,
    AdvocateProfile,
    BrandProfile,
    Campaign,
    CouponTier,
    CouponCode,
    Submission,
    AuthUser,
    SignupRequest,
    LoginRequest,
    CreateCampaignRequest,
    CreateSubmissionRequest,
    ApiResponse,
    PaginatedResponse,
} from '../../../shared/types';
